import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import ThirdPartyScripts from "@/components/ThirdPartyScripts";

export const metadata: Metadata = {
  title: "Pradeep - Resume",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"], // Specify subsets
  weight: ["300", "400", "500", "600", "700"], // Specify font weights (e.g., regular, bold)
  style: ["normal", "italic"], // Specify styles if needed
  display: "swap", // Use font-display: swap for performance
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-lt-installed="true" className={poppins.className}>
      <body>
        {children}
        <ThirdPartyScripts />
      </body>
    </html>
  );
}
